### PR TITLE
Create initial module

### PR DESCRIPTION
**Pull request by duboisph**

### CODE REVIEW

**Review by simonrondelez — APPROVED** [review]

**Review by iuriaranda — APPROVED** [review]

**Comment by MattiasGees** [comment]
@duboisph is it possible that you didn't give your ELK stack IAM access rights? You will need those to write your backups as well as to do your server discovery.

**Review by MattiasGees — CHANGES_REQUESTED** [review]
I see no IAM rights.

**Comment by duboisph** [comment]
@MattiasGees You are correct! We talked about them but forgot to add them :o.

**Comment by MattiasGees** [comment]
Now you can add them, I am happy to remind you ;)

**Comment by iuriaranda** [comment]
@MattiasGees I've created the IAM policy and attached to the EC2 instances. Can you review again?

**Review by MattiasGees — APPROVED** [review]
This looks ok, but you can do the IAM policy a lot cleaner with data resources in my opinion.

More information about an IAM policy doc https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html

**Pull request merged**
